openapi: 3.0.0
info:
  title: Zapbo Cred API
  description: API para gerenciamento de mensagens e usuários.
  version: 1.0.0
servers:
  - url: http://localhost:3004/
    description: Zapbo Cred API Server

paths:
  /:
    post:
      summary: Cria usuários a partir de um arquivo JSON
      description: Lê um arquivo JSON armazenado na pasta `temp/` e insere os usuários no banco de dados.
      responses:
        "201":
          description: Usuários criados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indica se os usuários foram criados com sucesso.
                  message:
                    type: string
                    description: Mensagem de confirmação.
        "500":
          description: Erro no servidor

  /sendToMany:
    post:
      summary: Envia uma mensagem com foto para todos os números armazenados
      description: Envia uma mensagem de texto e foto para todos os números registrados no banco de dados. Nenhum dado adicional é necessário na requisição.
      responses:
        "200":
          description: Mensagens enviadas com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indica se as mensagens foram enviadas com sucesso.
                  message:
                    type: string
                    description: Mensagem de confirmação.
        "500":
          description: Erro no servidor
