openapi: 3.0.0
info:
  title: Zapbo Cred API
  description: API para gerenciar números de mensagens.
  version: 1.0.0
servers:
  - url: http://localhost:3004/
    description: zapbo-cred API server

paths:
  /:
    get:
      summary: Obtém todos os números
      description: Retorna uma lista de todos os números registrados.
      responses:
        "200":
          description: Lista de números obtida com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID do número.
                    number:
                      type: string
                      description: O número de telefone.
        "500":
          description: Erro no servidor

    post:
      summary: Adiciona uma lista de números
      description: Adiciona uma lista de números à lista de números registrados.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numbers:
                  type: array
                  description: Lista de números de telefone a serem adicionados.
                  items:
                    type: string
                    description: Um número de telefone válido.
      responses:
        "201":
          description: Números adicionados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  numbersAdded:
                    type: array
                    description: Lista dos números adicionados com sucesso.
                    items:
                      type: string
                      description: Número de telefone adicionado.
        "400":
          description: Dados inválidos fornecidos
        "500":
          description: Erro no servidor

  /sendToMany:
    post:
      summary: Envia uma mensagem com foto para todos os números armazenados.
      description: Envia uma mensagem de texto e foto para todos os números de telefone registrados no banco de dados. Nenhum dado adicional é necessário na requisição.
      responses:
        "200":
          description: Mensagens enviadas com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indica se as mensagens foram enviadas com sucesso.
                  message:
                    type: string
                    description: Mensagem de confirmação.
        "500":
          description: Erro no servidor

components:
  schemas:
    Number:
      type: object
      properties:
        id:
          type: integer
          description: ID do número.
        numbers:
          type: array
          description: Lista de números de telefone.
          items:
            type: string
            description: Um número de telefone válido.

    Message:
      type: object
      properties:
        message:
          type: string
          description: A mensagem de texto que será enviada junto com a foto.
