openapi: 3.0.3
info:
  title: API de Mensagens
  description: API para gerenciamento e envio de mensagens em massa ou individualmente
  version: 1.0.0

servers:
  - url: http://localhost:3004
    description: Servidor local de desenvolvimento

paths:
  /messages/create:
    post:
      summary: Adiciona números de clientes a partir de um arquivo JSON
      tags:
        - Mensagens
      responses:
        '200':
          description: Números adicionados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Nenhum cliente encontrado
        '500':
          description: Erro interno do servidor

  /messagessend-many:
    post:
      summary: Envia mensagens para múltiplos destinatários
      tags:
        - Mensagens
      responses:
        '200':
          description: Mensagens enviadas com sucesso
        '500':
          description: Erro ao enviar mensagens

  /sendToOne:
    post:
      summary: Envia uma mensagem para um único destinatário
      tags:
        - Mensagens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - telefone
                - msg
                - id_comanda
              properties:
                telefone:
                  type: string
                  example: "5511999999999"
                msg:
                  type: string
                  example: "Olá, tudo bem?"
                id_comanda:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: Mensagem enviada com sucesso
        '400':
          description: Dados inválidos
        '500':
          description: Erro ao enviar mensagem
